version: "3"

services:
  demo:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
  
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: quiz_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
